fedora_coreos_podman_task:
    podman_spawner_script:
       - podman --version
    compute_engine_instance:
       image_project: fedora-coreos-cloud
       image: family/fedora-coreos-stable
       platform: linux
