version_task:
    version_script:
       - python3 --version || dnf -y install python3
       - python3 setup.py develop --user
       - python3 -m avocado --version
    container:
        matrix:
          - image: fedora:30
          - image: fedora:29
          - image: registry.access.redhat.com/ubi8/ubi

freebsd_version_task:
    version_script:
       - python3 -m ensurepip
       - python3 -m pip install -r requirements-selftests.txt
       - python3 setup.py develop --user
       - python3 -m avocado --version
       - python3 -m unittest -v selftests/unit/test_astring.py selftests/unit/test_test.py
    freebsd_instance:
       image_family: freebsd-12-1

osx_version_task:
    version_script:
       - python3 -m pip install --user -r requirements-selftests.txt
       - python3 setup.py develop --user
       - python3 -m avocado --version
       - python3 -m unittest -v selftests/unit/test_astring.py selftests/unit/test_test.py
    osx_instance:
       image: catalina-xcode-12.0

windows_version_task:
    version_script:
       - python setup.py develop --user
       - python -m avocado --version
       - python -m unittest -v selftests/unit/test_astring.py selftests/unit/test_test.py
    windows_container:
       image: rkttu/python-nanoserver:3.8.2_1809
