centos_podman_task:
    podman_spawner_script:
       - dnf -y install podman
       - podman --version
    compute_engine_instance:
       image_project: cirrus-images
       image: family/centos-8
       platform: linux
