dist: xenial
language: python

env:
    - AVOCADO_PARALLEL_LINT=1
      AVOCADO_LOG_DEBUG=yes
      SELF_CHECK_CONTINUOUS=y
      AVOCADO_CHECK_LEVEL=1

matrix:
  include:

cache:
    directories:
        - $HOME/.cache/pip

addons:
  apt:
    packages:
    - libvirt-dev

install:
    - pip install -r requirements-selftests.txt

script:
    - make check
