dist: xenial
language: python

env:
    - AVOCADO_PARALLEL_LINT=1
      AVOCADO_LOG_DEBUG=yes
      SELF_CHECK_CONTINUOUS=y
      AVOCADO_CHECK_LEVEL=1

matrix:
  include:
    - os: osx
      osx_image: xcode10.13
      language: shell
      install:
        - rm -fr optional_plugins/runner_vm
        - pip3 install --upgrade pip
        - pip3 install -r requirements-selftests.txt

cache:
    directories:
        - $HOME/.cache/pip

addons:
  apt:
    packages:
    - libvirt-dev

install:
    - pip install -r requirements-selftests.txt

script:
    - make check
