dist: xenial
language: python

env:
    - AVOCADO_PARALLEL_LINT=1
      AVOCADO_LOG_DEBUG=yes
      SELF_CHECK_CONTINUOUS=y
      AVOCADO_CHECK_LEVEL=1

matrix:
  include:
    - os: windows
      language: shell
      install:
        - rm -fr optional_plugins/runner_vm
        - choco install make
        - choco install python3 --params "/InstallDir:C:\Python3"
        - dir C:\\Python3\\
        - C:\\Python3\\python -m pip install --upgrade pip
        - C:\\Python3\\python -m pip install -r requirements-selftests.txt
        - C:\\Python3\\python setup.py develop --user
      script:
        - C:\\Python3\\python -m avocado --help

cache:
    directories:
        - $HOME/.cache/pip

addons:
  apt:
    packages:
    - libvirt-dev

install:
    - pip install -r requirements-selftests.txt

script:
    - make check
