name: GH Actions

on:
  pull_request:
  workflow_dispatch:

jobs:
  egg_task_fedora_37:

    name: Egg task fedora:37
    runs-on: ubuntu-20.04
    container:
      image: fedora:37
    steps:
      - name: Install Python dependencies
        run: dnf -y install python3 python3-setuptools
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Test running avocado from eggs
        run: |
         python3 setup.py bdist_egg
         mv dist/avocado_framework-*egg /tmp
         python3 setup.py clean --all
         python3 -c 'import sys; import glob; sys.path.insert(0, glob.glob("/tmp/avocado_framework-*.egg")[0]); from avocado.core.main import main; sys.exit(main())' run /bin/true
         cd /tmp
         python3 -c 'import sys; from pkg_resources import require; require("avocado-framework"); from avocado.core.main import main; sys.exit(main())' run /bin/true


  egg_task_fedora_38:

    name: Egg task fedora:38
    runs-on: ubuntu-20.04
    container:
      image: fedora:38
    steps:
      - name: Install Python dependencies
        run: dnf -y install python3-setuptools
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Test running avocado from eggs
        run: |
         python3 setup.py bdist_egg
         mv dist/avocado_framework-*egg /tmp
         python3 setup.py clean --all
         python3 -c 'import sys; import glob; sys.path.insert(0, glob.glob("/tmp/avocado_framework-*.egg")[0]); from avocado.core.main import main; sys.exit(main())' run /bin/true
         cd /tmp
         python3 -c 'import sys; from pkg_resources import require; require("avocado-framework"); from avocado.core.main import main; sys.exit(main())' run /bin/true

  egg_task_ubi_8:

    name: Egg task ubi:8.8
    runs-on: ubuntu-20.04
    container:
      image: registry.access.redhat.com/ubi8/ubi:8.8
    steps:
      - name: Install Python dependencies
        run: dnf -y install python38 python38-setuptools
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Test running avocado from eggs
        run: |
         python3 setup.py bdist_egg
         mv dist/avocado_framework-*egg /tmp
         python3 setup.py clean --all
         python3 -c 'import sys; import glob; sys.path.insert(0, glob.glob("/tmp/avocado_framework-*.egg")[0]); from avocado.core.main import main; sys.exit(main())' run /bin/true
         cd /tmp
         python3 -c 'import sys; from pkg_resources import require; require("avocado-framework"); from avocado.core.main import main; sys.exit(main())' run /bin/true

  egg_task_ubi_9:

    name: Egg task ubi:9.2
    runs-on: ubuntu-20.04
    container:
      image: registry.access.redhat.com/ubi9/ubi:9.2
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Test running avocado from eggs
        run: |
         python3 setup.py bdist_egg
         mv dist/avocado_framework-*egg /tmp
         python3 setup.py clean --all
         python3 -c 'import sys; import glob; sys.path.insert(0, glob.glob("/tmp/avocado_framework-*.egg")[0]); from avocado.core.main import main; sys.exit(main())' run /bin/true
         cd /tmp
         python3 -c 'import sys; from pkg_resources import require; require("avocado-framework"); from avocado.core.main import main; sys.exit(main())' run /bin/true

  egg_task_debian_10:

    name: Egg task debian:10.10
    runs-on: ubuntu-20.04
    container:
      image: debian:10.10
    steps:
      - name: Install Python dependencies
        run: apt update && apt -y install python3 python3-setuptools
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Test running avocado from eggs
        run: |
         python3 setup.py bdist_egg
         mv dist/avocado_framework-*egg /tmp
         python3 setup.py clean --all
         python3 -c 'import sys; import glob; sys.path.insert(0, glob.glob("/tmp/avocado_framework-*.egg")[0]); from avocado.core.main import main; sys.exit(main())' run /bin/true
         cd /tmp
         python3 -c 'import sys; from pkg_resources import require; require("avocado-framework"); from avocado.core.main import main; sys.exit(main())' run /bin/true

  egg_task_debian_11:

    name: Egg task debian:11.0
    runs-on: ubuntu-20.04
    container:
      image: debian:11.0
    steps:
      - name: Install Python dependencies
        run: apt update && apt -y install python3 python3-setuptools
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Test running avocado from eggs
        run: |
         python3 setup.py bdist_egg
         mv dist/avocado_framework-*egg /tmp
         python3 setup.py clean --all
         python3 -c 'import sys; import glob; sys.path.insert(0, glob.glob("/tmp/avocado_framework-*.egg")[0]); from avocado.core.main import main; sys.exit(main())' run /bin/true
         cd /tmp
         python3 -c 'import sys; from pkg_resources import require; require("avocado-framework"); from avocado.core.main import main; sys.exit(main())' run /bin/true
