name: GH Actions

on:
  pull_request:
  workflow_dispatch:

jobs:
# Checks that Python packages builds succeeds

  package-build:
    name: Build Package (wheel/tarball) for Python ${{ matrix.python-version }}
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10.0, 3.11]
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build tarballs and wheels
      run: make -f Makefile.gh build-wheel
    - name: Save tarballs and wheels as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: tarballs_and_wheels
        path: ${{github.workspace}}/PYPI_UPLOAD/
        retention-days: 1
    - run: echo "🥑 This job's status is ${{ job.status }}."

  egg-build:
    name: Build Egg for Python ${{ matrix.python-version }} from ${{ matrix.plugin }}
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10.0, 3.11]
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build eggs
      run: make -f Makefile.gh build-egg
    - name: Save eggs as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: eggs
        path: ${{github.workspace}}/EGG_UPLOAD/
        retention-days: 1
    - run: echo "🥑 This job's status is ${{ job.status }}."
