name: Pre-release tests

on:
  # Runs at 5:00 UTC on Mondays
  schedule:
    - cron: "0 5 * * 1"
  workflow_dispatch:

jobs:

  avocado-pre-release:
    name: Avocado pre-release job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install avocado
        run: |
          sudo python3 -m pip install -r requirements-dev.txt
          python3 setup.py develop --user
      - name: Avocado pre-release job
        run: ./selftests/pre_release/jobs/pre_release.py
      - name: Save artifacts
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: job-results-pre-release
          path: /home/runner/avocado/job-results/
          retention-days: 1
